config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks" }

  root 'pages#index', :as => :new_user_session
  get '/' => 'pages#index', as: :root
  get '/user-guide' => 'pages#user_guide'

  get 'routes' => 'routes#index', as: :routes
  get 'routes/:id' => 'routes#show', as: :route

  resources :cart_items
  resources :orders
  resources :bills

  resources 'requests', controller: :route_requests

  get '/pay/credit_card/callback' => 'bills#credit_card_callback'

  get '/tasks/check_bill' => 'tasks#pending_bill_check_task'
  get '/tasks/bill_export' => 'tasks#bill_export', as: :bill_export
  get '/tasks/invoice_export' => 'tasks#invoice_export', as: :invoice_export

  require 'sidekiq/web'
  authenticate :admin_user, ->(u) { u.present? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/route_request.rb
class RouteRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :route
end

app/controllers/route_requests_controller.rb
class RouteRequestsController < ApplicationController
  before_action :authenticate_user!

  def new
    quantity_h = params[:schedule]
    quantity_h = {} if quantity_h.nil?

    total_count = Hash[ current_user.cart_items.map{|ci| [ci.schedule_id.to_s, ci.quantity.to_s] } ].merge(quantity_h).values.map(&:to_i).sum

    if total_count > 3
      flash[:error] = "一人限買三張車票"
      redirect_to cart_items_path
    else

      @route_request = RouteRequest.new
      route_id = params[:route_id]
      if route_id
        @route = Route.find_by(id: route_id)
      end
    end
  end

  def create
    @route_request = RouteRequest.create(request_params.merge({user: current_user}))
    if @route_request
      render :success
    else
      redirect_to :back
    end
  end

  private
    def request_params
      params.require(:route_request).permit(:name, :email, :phone_number, :route_id, :request_origin, :request_destination, :message, :departure_time)
    end
end

app/helpers/route_requests_helper.rb
module RouteRequestsHelper
end

app/views/route_requests/new.slim
/ name
/ email
/ phone_number
/ route_id
/ request_origin
/ request_destination
.container-fuild style="padding: 30px;"
  .row.row-inner-s.request-routes-form-block
    .col.s12.m12
      h4 我想要申請路線加開！

      = form_tag requests_path
        .row
          .input-field.col.s12
            = text_field_tag 'route_request[name]', nil, {id: 'route_request[name]', required: '', 'class': 'validate', value: current_user.name}
            = content_tag 'label', "姓名", { 'data-error': "錯誤", 'for': 'route_request[name]' }
        .row
          input-field.col.s12
            = content_tag 'label', "信箱", { 'data-error': "錯誤", 'for': 'route_request[email]' }
            = text_field_tag 'route_request[email]', nil, {id: 'route_request[email]', required: '', 'class': 'validate', value: current_user.email, 'type': 'email'}
        .row
          input-field.col.s12
            = content_tag 'label', "手機（選填）", {'for': 'route_request[phone_number]'}
            = text_field_tag 'route_request[phone_number]', nil, {id: 'route_request[phone_number]'}

        .row
          input-field.col.s12
            = content_tag 'label', "上車地點", { 'data-error': "錯誤" , 'for': 'route_request[request_origin]'}
            = text_field_tag 'route_request[request_origin]', nil, {id: 'route_request[request_origin]', required: '', 'class': 'validate', value: "#{@route && @route.origin}"}

        .row
          input-field.col.m14.s12
            = content_tag 'label', "下車地點（學校）", { 'data-error': "錯誤", 'for': 'route_request[request_destination]' }
            = text_field_tag 'route_request[request_destination]', nil, {id: 'route_request[request_destination]', required: '', 'class': 'validate'}

        h5 預計搭乘時間
        .row
          input-field.col.s8
            = datetime_select('route_request', 'departure_time', prompt: true)

        .row
          label for="route_request[message]" 其它想說的話
          textarea.materialize-textarea name="route_request[message]" id="route_request[message]"

          input type="hidden" name="route_request[route_id]" value="#{@route && @route.id}"

        = submit_tag '送出！', 'class': 'btn btn--large'

app/views/route_requests/success.slim
.container-fuild
  .row.row-inner-s
    .col.s12.m12
      h2 謝謝！

      p
        | 您的加開申請我們收到了！
      p
        | 當申請人數達標、路線加開成功時，我們會用電子郵件或是手機簡訊再次通知你
        br
        | 保持聯繫！
      p
        | 接下來您可以前往我們其它的服務逛逛，像是可愛俏皮迷人的
        a href="https://table.colorgy.io" 「Colorgy Table」
        | ，或是幾點都幫、什麼都幫、哪裡都幫的：
        a href="https://colorgytasks.io/" 「大學幫」
        | 。這些服務都期待你的一齊參予哦 ：D

      a.btn.btn--large.teal.darken-1 href=routes_path 逛逛其它路線