config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks" }

  root 'pages#index', :as => :new_user_session
  get '/' => 'pages#index', as: :root
  get '/user-guide' => 'pages#user_guide'

  get 'routes' => 'routes#index', as: :routes
  get 'routes/:id' => 'routes#show', as: :route

  resources :cart_items
  resources :orders
  resources :bills

  resources 'requests', controller: :route_requests

  get '/pay/credit_card/callback' => 'bills#credit_card_callback'

  get '/tasks/check_bill' => 'tasks#pending_bill_check_task'
  get '/tasks/bill_export' => 'tasks#bill_export', as: :bill_export
  get '/tasks/invoice_export' => 'tasks#invoice_export', as: :invoice_export

  require 'sidekiq/web'
  authenticate :admin_user, ->(u) { u.present? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/views/partials/_fb_sdk.slim
#fb-root

javascript:
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.4&appId=752440461479659";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

app/views/partials/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <script type="text/javascript">
    $(document).ready(function() {
      flash['<%= type %>']('<%= message %>');
    });
  </script>
<% end %>

app/views/partials/_footer.html.erb
<footer>
  <div class="footer-inner">
    <div class="footer-menu">
      <ul>
        <li><a href="http://misk.io" target="_blank">關於我們</a></li>
        <li><a href="https://www.facebook.com/pages/Colorgy/1529686803975150" target="_blank">聯絡我們</a></li>
        <li><a href="https://www.facebook.com/pages/Colorgy/1529686803975150" target="_blank">發落我們</a></li>
      </ul>
    </div>
    <div class="company-rights">
      <p><small><a href="https://github.com/colorgy/Bus" target="_blank">網站原始碼 ＠Github</a> - © Colorgy 2015</small></p>
    </div>
  </div>
</footer>

app/views/partials/_google_analytics.html.erb
<% if ENV['GOOGLE_ANALYTICS_ID'].present? %>
<% @view_google_analytics_ids = Rails.cache.fetch("view-google-analytics-ids") { ENV['GOOGLE_ANALYTICS_ID'].split(',') } %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  <% @view_google_analytics_ids.each_with_index do |id, i| %>
  <% i = i.to_s.tr('0-9', 'a-z') %>
  ga("create", "<%= id %>", 'auto', {'name': "<%= i %>"});
  ga("<%= i %>.require", 'displayfeatures');
  <% if current_user %>
  ga("<%= i %>.set", '&uid', "<%= current_user.id %>");
  <% end %>
  ga("<%= i %>.send", 'pageview');
  <% end %>
</script>
<% end %>

app/views/partials/_navbar.slim
nav.colorgy-nav.nav-fixed
  .top
    .top-bar
      ul
        li
          a href="https://colorgy.io" target="_blank" Colorgy 首頁
        li
          a href="https://table.colorgy.io" target="_blank" TABLE
        li
          a href="https://books.colorgy.io" target="_blank" BOOKS
        li
          a href="https://colorgytasks.io" target="_blank" TASKS
        li
          a href="#{cart_items_path}"
            i.material-icons.list-icon> shopping_cart
            | 購物車
            = current_user && "(#{current_user.cart_items_count})"
        - if current_user.blank?
          li.login-btn
            a href="#{user_omniauth_authorize_path(:colorgy)}"
              | Colorgy 登入
        - else
          li.nav-bar-drop-down
            a href="#"
              = "Hi, #{current_user.name}"
              i.material-icons.list-icon style=("color: #fff;")  expand_more
            ul.drop-down-list style=("margin-top: -1px;")
              li
                a href="#{sign_out_url}"
                  | 登出

  .nav-wrapper
    a.brand-logo href="#{root_path}"
      = image_tag 'BUS.svg'
    a.button-collapse data-activates="mobile-demo" href="/"
      i.material-icons dehaze

    ul.right.hide-on-med-and-down.main-nav
      li
        a.tooltipped data-delay="0" data-position="bottom" data-tooltip="尋找你想要的路線、班次" href="#{routes_path}"
          i.material-icons.list-icon directions_bus
          | 路線瀏覽
      li
        a.tooltipped data-delay="0" data-position="bottom" data-tooltip="檢視你訂購的票券" href="#{bills_path}"
          i.material-icons.list-icon list
          | 我的帳單
      li
        a.tooltipped data-delay="0" data-position="bottom" data-tooltip="不知道怎麼訂嗎？看一下購物流程吧" href="#{user_guide_path}"
          i.material-icons.list-icon subject
          | 購物流程
      li.nav-bar-drop-down
        a href="#"
          i.material-icons.list-icon more_vert


    ul#mobile-demo.side-nav
      - if current_user.blank?
        li.login-btn
          a href="#{user_omniauth_authorize_path(:colorgy)}"
            | Colorgy 登入
      - else
        li#personal-menu style="background-color: rgb(151), 151, 151) !important;"
          .personal-avatar
            = image_tag current_user.avatar_url
          a href="#personal-menu"
            = current_user.name
      li
        a href="#{routes_path}"
          | 路線瀏覽
      li
        a href="#{bills_path}"
          | 我的帳單
      li
        a href="#{user_guide_path}"
          | 購物流程
      li
        a href="#{sign_out_url}"
          | 登出

    .clear style="clear:both;"

javascript:
  $('#personal-menu').click(function(){
    $('.personal-menu-collapse').slideToggle(500);
    if($('.personal-menu-trigger').html() == 'keyboard_arrow_down'){
      $('.personal-menu-trigger').html('keyboard_arrow_up');
    }
    else{
      $('.personal-menu-trigger').html('keyboard_arrow_down');
    }
  })
  $('.login-btn').click(function(){
    $('#perloader-wrapper').addClass('active');
  })

app/views/partials/_orders_table.slim
table.cart-table
  thead
    th 路線
    th 出發時間
    th 單價
    / th
  - @orders.each do |order|
    tr
      td= order.schedule && order.schedule.route.display_name
      td= order.schedule && departure_time_format(order.schedule.departure_time)
      td= order.schedule && order.schedule.route.price

app/views/partials/_uservoice.html.erb
<% if ENV['USERVOICE_API_KEY'].present? %>

  <%= javascript_tag do %>

    UserVoice=window.UserVoice||[];(function(){var uv=document.createElement('script');uv.type='text/javascript';uv.async=true;uv.src='//widget.uservoice.com/<%= ENV['USERVOICE_API_KEY'] %>.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(uv,s)})();

    UserVoice.push(['set', {
      accent_color: '#448dd6',
      trigger_color: 'white',
      trigger_background_color: 'rgba(46, 49, 51, 0.6)'
    }]);

    <% if current_user %>
    UserVoice.push(['identify', {
      email:      '<%= current_user.email %>',
      name:       '<%= current_user.name %>',
      created_at: <%= current_user.created_at.to_i %>,
      id:         <%= current_user.sid %>,
      type:       '<%= current_user.identity %>',
    }]);
    <% end %>

    UserVoice.push(['addTrigger', { mode: 'contact', trigger_position: 'bottom-right' }]);

    UserVoice.push(['autoprompt', {}]);

  <% end %>

<% end %>