config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks" }

  root 'pages#index', :as => :new_user_session
  get '/' => 'pages#index', as: :root
  get '/user-guide' => 'pages#user_guide'

  get 'routes' => 'routes#index', as: :routes
  get 'routes/:id' => 'routes#show', as: :route

  resources :cart_items
  resources :orders
  resources :bills

  resources 'requests', controller: :route_requests

  get '/pay/credit_card/callback' => 'bills#credit_card_callback'

  get '/tasks/check_bill' => 'tasks#pending_bill_check_task'
  get '/tasks/bill_export' => 'tasks#bill_export', as: :bill_export
  get '/tasks/invoice_export' => 'tasks#invoice_export', as: :invoice_export

  require 'sidekiq/web'
  authenticate :admin_user, ->(u) { u.present? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController


  def index
    if current_user.blank?
      flash[:error] = "請先登入才能進行此操作"
      redirect_to :back
    else
      @cart_items = current_user.cart_items
      @title = "購物車"
    end
  end

  def create
    if current_user.blank?
      flash[:error] = "請先登入才能進行此操作"
      redirect_to :back
    else
      schedule_id = params[:schedule][:id]
      schedule = Schedule.find_by(id: schedule_id)
      quantity = params[:schedule][:quantity].to_i

      user_cart_items = current_user.cart_items

      total_count = user_cart_items.map(&:quantity).sum + quantity

      if total_count > 3
        flash[:error] = "一次限購三張車票"
        redirect_to :back
      elsif !schedule.is_available?
        flash[:error] = "此班次不可取得"
        redirect_to :back
      elsif user_cart_items.count > 0 && !user_cart_items.pluck(:schedule_id).include?(schedule_id)
        flash[:error] = "一次限購一種班次，購物車已清空，請再加入一次"
        current_user.cart_items.destroy_all
        redirect_to :back
      else

        begin
          ActiveRecord::Base.transaction do
            current_user.add_to_cart!(schedule: schedule, quantity: quantity)
          end
          flash[:success] = "成功加入購物車"
        rescue ActiveRecord::RecordInvalid
          # 基本不會發生，前端被亂改的時候
          flash[:error] = "不能坐太多哦"
        end

        redirect_to :back
      end
    end
  end

  ## deprecated method
  def update_cart
    if current_user.blank?
      flash[:error] = "請先登入才能進行此操作"
      redirect_to :back
    else
      quantity_h = params[:schedule]
      total_count = Hash[ current_user.cart_items.map{|ci| [ci.schedule_id.to_s, ci.quantity.to_s] } ].merge(quantity_h).values.map(&:to_i).sum

      if total_count > 3
        flash[:error] = "一人限買三張車票"
        redirect_to :back
      else

        Schedule.where(id: params[:schedule].keys).each do |schedule|
          current_user.add_to_cart!(schedule: schedule, quantity: quantity_h[schedule.id.to_s].to_i)
        end
        flash[:notice] = "購物車更新成功"
        redirect_to cart_items_path
      end
    end
  end

  def destroy
    if current_user.blank?
      flash[:error] = "請先登入才能進行此操作"
      redirect_to :back
    else
      @cart_item = current_user.cart_items.find(params[:id]).destroy!
      flash[:success] = "成功從購物車中移除"
      redirect_to :back
    end
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.slim
.container-fluid
  .row.row-inner-s
    - if @cart_items.count == 0
      .page-sorry-message
        i.material-icons.large-icon>shopping_cart
        p = '您的購物車目前是空的'
        = link_to "前往購買車票", routes_path, class: 'btn btn--large'
    - else
      = form_tag orders_path
        .cart
          table.cart-table
            thead
              tr
                th 路線
                th 出發時間
                th 張數
                / th 座號
                th
            tbody
              - @cart_items.each do |cart_item|
                tr
                  td = cart_item.route.short_name
                  td = departure_time_format(cart_item.schedule.departure_time)
                  td = cart_item.quantity
                  td = link_to '移除', cart_item_path(cart_item), method: :delete
                  input type="hidden" name="schedule[#{cart_item.schedule_id}]" value="#{cart_item.quantity}"

        = link_to '查看更多路線', routes_path, class: 'btn btn--large grey darken-2'

        - unless current_user.cart_items_count.zero?
          = submit_tag '已確認，下一步', class: 'btn btn--large', style: "margin-left: 10px; float: right;"