config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks" }

  root 'pages#index', :as => :new_user_session
  get '/' => 'pages#index', as: :root
  get '/user-guide' => 'pages#user_guide'

  get 'routes' => 'routes#index', as: :routes
  get 'routes/:id' => 'routes#show', as: :route

  resources :cart_items
  resources :orders
  resources :bills

  resources 'requests', controller: :route_requests

  get '/pay/credit_card/callback' => 'bills#credit_card_callback'

  get '/tasks/check_bill' => 'tasks#pending_bill_check_task'
  get '/tasks/bill_export' => 'tasks#bill_export', as: :bill_export
  get '/tasks/invoice_export' => 'tasks#invoice_export', as: :invoice_export

  require 'sidekiq/web'
  authenticate :admin_user, ->(u) { u.present? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :schedules, dependent: :destroy
  has_many :cart_items, class_name: 'UserCartItem', dependent: :destroy

  has_many :subroutes, class_name: 'Route', foreign_key: :parent_id
  belongs_to :parent, class_name: 'Route', foreign_key: :parent_id

  has_many :route_requests

  scope :root, -> { where(parent: nil) }
  scope :not_root, -> { where.not(parent: nil) }
  scope :not_hidden, -> { where(hidden: false) }

  accepts_nested_attributes_for :schedules, :subroutes, allow_destroy: true

  validates_inclusion_of :direction, in: %w(North South)

  def display_name
    "#{origin} 到 #{destination}"
  end

  def short_name
    "#{origin} - #{destination}"
  end

  def is_available?
    self.is_available
  end

  def is_full?
    self.fake_full
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  # before_action :authenticate_user!, only: [:show]

  def index
    if params[:root_route]
      @root_route = Route.root.not_hidden.find_by(id: params[:root_route])

      if @root_route.present?
        # The 支線
        @routes = @root_route.subroutes.not_hidden
        @title = @root_route.short_name
        @h4 = "從 #{@root_route.display_name} 的所有支線"
        render :subroutes
      else
        @route = Route.not_hidden.find_by(id: params[:root_route])
        if @route.present? && @route.parent.present?
          # it's subroute
          redirect_to route_path(@route)
        else
          redirect_to routes_path
        end
      end
    else
      @routes = Route.not_hidden.root.order(:direction)
      @title = "路線總覽"
    end
  end

  def show
    @route = Route.not_hidden.find_by(id: params[:id])

    if @route.nil?
      flash[:error] = "路線不存在！"
      redirect_to routes_path
    elsif @route.parent.nil?
      # it's a root route
      redirect_to routes_path, root_route: @route.id
    else
      @title = @route.short_name
      @root_route = @route.parent
    end
  end
end

app/helpers/routes_helper.rb
module RoutesHelper
  def render_schedule_radio schedule
    classes = {
      requrie: ''
    }.merge((schedule.is_available? && schedule.available?) ?  {} : {disabled: ''})

    radio_button("schedule", "id", schedule.id, classes)
  end

  def render_available_seats schedule, user: nil
    if schedule.is_full?
      "班次已售完！"
    else
      seat_count = schedule.is_faked? ? schedule.fake_seats_no : schedule.available_seats_count
      if !user.nil? && schedule.is_faked?
        seat_count -= user.orders.ordered.where(schedule: schedule).count
        seat_count = 0 if seat_count < 0
      end
      "還剩 #{seat_count} 位"
    end
  end

  def render_route_class route
    classes = []
    classes << (route.is_available? ? "available" : "not-available")
    classes << (route.is_full? ? "full" : nil)
    classes.join(' ')
  end
end

app/views/routes/index.slim
.container-fuild
  .row
    .routes-field
      .routes-field-bg
      .routes-field-skew-bg
      h4.routes-field-title
        i.material-icons> directions_bus
        = '精選路線'
      p.routes-field-description = '以下是 Colorgy Bus 目前提供之精選路線，挑一個你想要的吧！'
      .line
      - @routes.each do |route|
        li.route-list-item
          a href=routes_path(root_route: route.id)
            span.hot-label = "HOT! NT$ #{route.price}"
            h5.route-list-header
              = route.display_name
              i.material-icons> keyboard_arrow_right
        br
      .line
      .apply-add-field
        p = '沒有你想要的路線？連署加開吧！'
        br
        = link_to '我要申請加開路線' ,href="#{new_request_path(route_id: (@root_route && @root_route.id))}", class: 'btn btn--large'

app/views/routes/show.slim
.content-strip.image-strip
  .content-strip-cover
  .content-strip-inner
    h4.strip-title= @route.short_name || "路線瀏覽"
    p.strip-description '選擇班次與購買票數並加入購物車'
.container-fuild
  .row.row-inner-s
    .card.route-show-field
      h4= @route.short_name
      p.description
        i class="material-icons"
          = 'info_outline'
        | 本車次不劃位入座，採上車看到空位即可入座
      p.description
        i class="material-icons"
          = 'flag'
        = @route.description.html_safe

      = form_tag(cart_items_path, method: :post)
        label.schedule-label = '請選擇您想要的班次'
        - @route.schedules.not_hidden.each do |schedule|
          .row.schedule-item
            .col.s6
              = render_schedule_radio(schedule)
              label for="schedule_id_#{schedule.id}" = "路線時間: #{departure_time_format(schedule.departure_time)}"

            .col.s6
              = render_available_seats(schedule, user: current_user)

        .row
          .col.s12
            .shopping-actions
              label = '購買票數'
              /input type="number" name="schedule[quantity]" min="1" max="3" value="1"
              select class="browser-default" name="schedule[quantity]"
                option value="" disabled="" selected=""
                  = '選擇購買票數'
                option value="1"
                  = '1張'
                option value="2"
                  = '2張'
                option value="3"
                  = '3張'

        br

        / - if current_user
        button.btn.btn--large type="submit" class="add-to-cart-btn"
          i.material-icons.list-icon style="color: #fff;" shopping_cart
          | 放入購物車
        / - else
        /   a.btn.btn--large href=user_omniauth_authorize_path(:colorgy)
        /     i.material-icons.list-icon style="color: #fff;" shopping_cart
        /     | 放入購物車

        br
        br
        - unless current_user && current_user.cart_items.empty?
          a.btn.btn--large.light-blue.darken-1 href="#{cart_items_path}"
            i.material-icons.list-icon style="color: #fff;" forward
            | 前往結帳去


javascript:
  $('.add-to-cart-btn').click(function(){
    var selected_radio_count = $('input[type="radio"]:checked').length;
    var select_value = $('select[name="schedule[quantity]"] option:selected').val();
    if(selected_radio_count == 0){
      flash.error('你要選擇班次才能加入購物車唷！');
      return false;
    }
    if( select_value != '1' && select_value != '2' && select_value != '3'){
      flash.error('你沒有選擇要買的張數唷！');
      return false;
    }
  })

app/views/routes/subroutes.slim
.content-strip.image-strip
  .content-strip-cover
  .content-strip-inner
    a href="#{route_path(@root_route)}"
      h4.strip-title= @h4 || "路線瀏覽"
    p.strip-description 點擊你想要的路線查看班次吧！
.container-fuild
  .row.row-inner
    .routes-container
      - @routes.each do |route|
        .col.s12.m4
          .route-item.hot class=render_route_class(route)
            .route-item-bg
            .route-item-inner
              h5.route-display-name
                i.material-icons> directions_bus
                = link_to route.display_name, routes_path(root_route: route.id)
              div style="text-align: left;"
                h5.route-price
                  = "票價 NT$ #{route.price} "
              p.route-description
                = route.description.html_safe
              div style="clear: both;"
              div style="text-align: right;"
                .fb-share-button data-layout="button"
                a.view-schedules-btn.btn.grey.darken-2 href=routes_path(root_route: route.id)
                  | 查看班次
      div style="clear: both;"
    div style="text-align: center; padding: 0 0 80px 0;"
      a.btn.btn--large.tooltipped href="#{new_request_path(route_id: (@root_route && @root_route.id))}" data-delay="0" data-position="top" data-tooltip="想搭的路線自己申請！"
        | 我要申請路線

javascript:
  $(document).ready(function(){
    $('.collapsible-header:first').addClass('active');
    $('.collapsible').collapsible({
      accordion : false // A setting that changes the collapsible behavior to expandable instead of the default accordion style
    });
  });